[package]
name = "special"
version = "0.1.0"
authors = ["Mizar <mizar.jp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddreal = { path = "../ddreal" }
num = "0.2"
